### ISSUE TITLE
[PE-D] Different Command Input Format in Application and User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W13-3/tp#178]
The command format specified in the User is Different from that of the application.

![image.png](https://raw.githubusercontent.com/Siddharth-Sid/ped/main/files/1c549cbe-f400-421b-988e-216f26e103d9.png)

![image.png](https://raw.githubusercontent.com/Siddharth-Sid/ped/main/files/f7d7b7bb-6da2-4c5e-9307-fd38413b38c2.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Siddharth-Sid/ped#6

**Comment by yzhilong** [comment]
Similar issue as https://github.com/AY2122S1-CS2103T-W13-3/tp/issues/169. Will be fixed together.
