### ISSUE TITLE
[PE-D] Negative initial cash field not invalid

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W13-3/tp#182]
e.g. `add /g b2 /s-0 /e0`
shows up as 

![image.png](https://raw.githubusercontent.com/Chesterwongz/ped/main/files/9e38b36e-2b38-42a4-893e-f769a17249a5.png)

Expected:
-0 is invalid, or shown as + $0.00

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Chesterwongz/ped#10

**Comment by yzhilong** [comment]
Fixed in PR
