### ISSUE TITLE
[PE-D] UG provided edit example does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W13-3/tp#183]
edit 3 /s 1 /loc John’s house

![image.png](https://raw.githubusercontent.com/ryantianj/ped/main/files/9ca0fe13-35ac-4251-b2f7-61ef6a3f54ab.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: ryantianj/ped#12

**Comment by chingh20** [comment]
Same as #181 .
