### ISSUE TITLE
[PE-D] Large numbers break the GUI

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W13-3/tp#190]
Adding an entry with an astronomically large number breaks the GUI, e.g.:

![image.png](https://raw.githubusercontent.com/Chesterwongz/ped/main/files/d883e2b3-e650-48ff-9c6d-316fda399644.png)

And it remains broken after clearing entries

![image.png](https://raw.githubusercontent.com/Chesterwongz/ped/main/files/69cf9422-4803-4561-9151-ce3013b3926e.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: Chesterwongz/ped#14

**Comment by yzhilong** [comment]
I think we can just set a limit on how big the amount entered can be? Since large numbers, say over 1E12 are completely unrealistic anyways.
