### ISSUE TITLE
[PE-D] Bug in Add Command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W13-3/tp#197]
Incorrect Input Add Command

Steps:
* Start application
* Insert the following add command taken from the User Guide Provided:

Command: `add /g poker /p100 /tag`

Shows Command Success, however, I think an error should be thrown for empty input.

![image.png](https://raw.githubusercontent.com/Siddharth-Sid/ped/main/files/a5849252-3964-4d15-b3bc-076aba12a0ea.png)

![image.png](https://raw.githubusercontent.com/Siddharth-Sid/ped/main/files/e95f5b6d-53ad-4972-9e52-b6a896388a3d.png)

![image.png](https://raw.githubusercontent.com/Siddharth-Sid/ped/main/files/93282d53-cb71-45b7-b03c-f5b2770d0bf6.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Siddharth-Sid/ped#9

**Comment by chingh20** [comment]
Same as #198
