### ISSUE TITLE
[PE-D] Bug in the Displayed Char

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W13-3/tp#201]
Possible error in the Chart

The profit shown for the date is 100 however based on data populated it should be 200

![image.png](https://raw.githubusercontent.com/Siddharth-Sid/ped/main/files/2f55d05a-6e20-4316-a1d5-38f8be6a013c.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Siddharth-Sid/ped#13

**Comment by chingh20** [comment]
Same as #187. Maybe change it to average profit per game?
