### ISSUE TITLE
Add command duration is wrong for large numbers

### ISSUE THREAD

**Issue by sherrpass** [AY2122S1-CS2103T-W13-3/tp#242]
Reproduce:
1) add /g poker /s 1000000000 e/ 1000000000 /date 2021-09-11 21:20 /dur 1000000000:14 /loc Home

Expected:
Creates a game with a game duration of 1000000000h 14 min

Actual:
Creates a game with game duration of 28417211h 58min

![image](https://user-images.githubusercontent.com/49825021/140651084-83f5efde-38bd-409c-b172-9b6482e2ab54.png)

**Comment by BenjaminLHR** [comment]
Thanks, we have fixed it
